name = "fedjaj-collector"
main = "infra/collector-worker.js"
compatibility_date = "2024-01-01"
account_id = "a7e3a72ef43984dc05bef12300d641c6"

[vars]

# KV namespace binding
[[kv_namespaces]]
binding = "KV"
id = "dba9293f104a4474959a909e27777046"